//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 09:40:22 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ws.oee.equipmentSave", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ws.oee;
