//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 10:02:33 AM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ordemProducao.ws.oee.tc.feevale.br", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ws.oee.ordemProducao.inclusao.types;
