//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 07:53:32 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ordemProducao.ws.oee.tc.feevale.br", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ws.oee.ordemProducao.types;
