//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 01:57:24 PM BRST 
//


package ws.oee.apontamento.inserirAlterarApontamentoQuantidade.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{apontamento.ws.oee.tc.feevale.br}codigo"/>
 *         &lt;element ref="{apontamento.ws.oee.tc.feevale.br}codigoOrdemProducao"/>
 *         &lt;element ref="{apontamento.ws.oee.tc.feevale.br}dataHora"/>
 *         &lt;element ref="{apontamento.ws.oee.tc.feevale.br}quantidade"/>
 *         &lt;element ref="{apontamento.ws.oee.tc.feevale.br}qualidadeProducao"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codigo",
    "codigoOrdemProducao",
    "dataHora",
    "quantidade",
    "qualidadeProducao"
})
@XmlRootElement(name = "inserirOuAlterarApontamentoQuantidadeRequest")
public class InserirOuAlterarApontamentoQuantidadeRequest {

    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer codigo;
    protected int codigoOrdemProducao;
    @XmlElement(required = true)
    protected DataHora dataHora;
    protected double quantidade;
    @XmlElement(required = true)
    protected String qualidadeProducao;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodigo(Integer value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the codigoOrdemProducao property.
     * 
     */
    public int getCodigoOrdemProducao() {
        return codigoOrdemProducao;
    }

    /**
     * Sets the value of the codigoOrdemProducao property.
     * 
     */
    public void setCodigoOrdemProducao(int value) {
        this.codigoOrdemProducao = value;
    }

    /**
     * Gets the value of the dataHora property.
     * 
     * @return
     *     possible object is
     *     {@link DataHora }
     *     
     */
    public DataHora getDataHora() {
        return dataHora;
    }

    /**
     * Sets the value of the dataHora property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataHora }
     *     
     */
    public void setDataHora(DataHora value) {
        this.dataHora = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     */
    public double getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     */
    public void setQuantidade(double value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the qualidadeProducao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualidadeProducao() {
        return qualidadeProducao;
    }

    /**
     * Sets the value of the qualidadeProducao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualidadeProducao(String value) {
        this.qualidadeProducao = value;
    }

}
