//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.21 at 01:57:24 PM BRST 
//


package ws.oee.apontamento.inserirAlterarApontamentoQuantidade.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ws.oee.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Erros_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "erros");
    private final static QName _CodigoOrdemProducao_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "codigoOrdemProducao");
    private final static QName _Quantidade_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "quantidade");
    private final static QName _Codigo_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "codigo");
    private final static QName _QualidadeProducao_QNAME = new QName("apontamento.ws.oee.tc.feevale.br", "qualidadeProducao");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ws.oee.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InserirOuAlterarApontamentoQuantidadeRequest }
     * 
     */
    public InserirOuAlterarApontamentoQuantidadeRequest createInserirOuAlterarApontamentoQuantidadeRequest() {
        return new InserirOuAlterarApontamentoQuantidadeRequest();
    }

    /**
     * Create an instance of {@link DataHora }
     * 
     */
    public DataHora createDataHora() {
        return new DataHora();
    }

    /**
     * Create an instance of {@link InserirOuAlterarApontamentoQuantidadeResponse }
     * 
     */
    public InserirOuAlterarApontamentoQuantidadeResponse createInserirOuAlterarApontamentoQuantidadeResponse() {
        return new InserirOuAlterarApontamentoQuantidadeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "apontamento.ws.oee.tc.feevale.br", name = "erros")
    public JAXBElement<String> createErros(String value) {
        return new JAXBElement<String>(_Erros_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "apontamento.ws.oee.tc.feevale.br", name = "codigoOrdemProducao")
    public JAXBElement<Integer> createCodigoOrdemProducao(Integer value) {
        return new JAXBElement<Integer>(_CodigoOrdemProducao_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "apontamento.ws.oee.tc.feevale.br", name = "quantidade")
    public JAXBElement<Double> createQuantidade(Double value) {
        return new JAXBElement<Double>(_Quantidade_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "apontamento.ws.oee.tc.feevale.br", name = "codigo")
    public JAXBElement<Integer> createCodigo(Integer value) {
        return new JAXBElement<Integer>(_Codigo_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "apontamento.ws.oee.tc.feevale.br", name = "qualidadeProducao")
    public JAXBElement<String> createQualidadeProducao(String value) {
        return new JAXBElement<String>(_QualidadeProducao_QNAME, String.class, null, value);
    }

}
